Create Capstone project
shaqayq/Library pull request #1
Opened 2022-06-24 14:09 UTC by shaqayq

It's the first capstone project for the library.

2022-06-24 17:23 UTC, codepantha requested changes
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @shaqayq 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/nKN7E76a27Uek/giphy.gif"/>

### Highlights 🎯 
✔️ Correct Github flow
✔️ Linter checks
✔️ Good design

## Required Changes ♻️
_Check the comments under the review._

- [ ] Modify your PR description to be more descriptive. Here you can give a very brief explanation of what you've done and why you've done it 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 17:23 UTC, codepantha commented on README.md
>  - etc
- [ ] Please ensure to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the author of the original design as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-06-24 17:23 UTC, codepantha commented on about.html
> +                    Welcome to Faena Aleph, an editorial pulse which,
- [ ] On the mobile view, this `home-content` section is overlapping with the hamburger button. Please add some margin-top or try some other means to make it look more like the given design shown below 👇 
## Your Design
![image](https://user-images.githubusercontent.com/46839548/175576240-3c059e6f-e1a5-46c7-aa59-5b62c048d346.png)
## Behance Design
![image](https://user-images.githubusercontent.com/46839548/175576300-cc623eda-d97a-4c70-9c0f-e850f6b08603.png)

- [ ] Please make the background transparent or use the same pattern as the top section background

2022-06-24 17:23 UTC, codepantha commented on index.html
> +        </section>
- [ ] Your footer section does not look like the given Behance design. In fact, this section should be partner/sponsors section.
- [ ] Add a footer section using a `<footer>` tag. It should contain a logo aligned to the left and text aligned to the right.

2022-06-24 17:23 UTC, codepantha commented on index.html
> +        </section>
- [ ] The `<h5>` should be a paragraph tag
- [ ] The `<h3>` **"There are also twenty public libraries"** is the title of your page and should be a `<h1>` tag according to semantic HTML
### Your Design
![image](https://user-images.githubusercontent.com/46839548/175601685-f36a9309-3c6f-461c-96a0-e660abacf22b.png)
### Behance Design
![image](https://user-images.githubusercontent.com/46839548/175602506-1d812584-bf30-4956-9145-63d1dbb91499.png)

2022-06-24 17:23 UTC, codepantha commented on index.html
> +                 </ul>
- [ ] Please use `<article>` tags in place of the `<ul>`. each card here should be an article as it is semantically more correct than using an unordered list 🙏 
- [ ] You currently have 4 articles instead of 5. Kindly add one more according to project requirements

2022-06-24 17:23 UTC, codepantha commented on script.js
> +  intro.innerHTML = author[key].introduction;
- [ ] Please make the author intro a paragraph text and not a <hx> tag

2022-06-24 17:23 UTC, codepantha commented on script.js
> +  content.appendChild(info);
- [ ]  This info div represents the individual author cards and should be an <article> instead using semantic HTML 🙏

2022-06-24 17:23 UTC, codepantha commented on script.js
> +  book.innerHTML = author[key].books;
- [ ] Please make the book info a paragraph text and not a `<h6>` tag

2022-06-24 17:23 UTC, codepantha commented on script.js
> +  image.src = author[key].pic;
- [ ] Please add a patterned image as a background for this image. Also make it appear at the top-left corner of the image 😎

2022-06-24 17:23 UTC, codepantha commented on about.html
> +                Here we perceive ourselves as a garden of shared imagination, an opportunity
- [ ] This section looks too squished together. Please apply some margins and try to make it look more like the Behance design 👍 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/175609491-8906e2a5-eaa8-47df-af79-ae4fa12e3d6a.png)
### Behance Design
![image](https://user-images.githubusercontent.com/46839548/175609724-2631962a-2689-4d46-a6f6-75e6e1758a47.png)

2022-06-24 21:24 UTC, shaqayq commented on README.md
>  - etc
Thank you for your feedback, can you explain this feedback?

2022-06-25 10:13 UTC, EricMbouwe approved these changes
Hi @shaqayq, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-06-25 10:18 UTC, merged